version: "3"

services:
  api:
    container_name: cboe-api-1
    build:
      dockerfile: Dockerfile.api
    ports:
      - 8001:8001
    networks:
      - cboe
    restart: always
    depends_on:
      - redis
      - postgres
  client:
    container_name: cboe-client-1
    build:
      dockerfile: Dockerfile.client
    tty: true
    ports:
      - 3000:3000
    networks:
      - cboe
    restart: always
    depends_on:
      - api
  postgres:
    container_name: cboe-postgres-1
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cboe
    ports:
      - 5432:5432
    networks:
      - cboe
    volumes:
      - cboe-postgres:/var/lib/postgresql/data
    restart: always
  redis:
    container_name: cboe-redis-1
    image: redis
    ports:
      - 6379:6379
    networks:
      - cboe
    volumes:
      - cboe-redis:/data
    restart: always

networks:
  cboe:
    driver: bridge

volumes:
  cboe-redis:
  cboe-postgres:
