version: "3"

services:
  postgres:
    container_name: cboe-postgres-1
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cboe
    ports:
      - 5432:5432
    networks:
      - cboe
    volumes:
      - cboe-postgres:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: cboe-redis-1
    image: redis
    ports:
      - 6379:6379
    networks:
      - cboe
    volumes:
      - cboe-redis:/data
    restart: always

networks:
  cboe:
    driver: bridge

volumes:
  cboe-redis:
  cboe-postgres:


