version: "3"

services:
  postgres:
    container_name: cbeo-postgres-1
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cbeo
    ports:
      - 5432:5432
    networks:
      - cbeo
    volumes:
      - cbeo-postgres:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: cbeo-redis-1
    image: redis
    ports:
      - 6379:6379
    networks:
      - cbeo
    volumes:
      - cbeo-redis:/data
    restart: always

networks:
  cbeo:
    driver: bridge

volumes:
  cbeo-redis:
  cbeo-postgres:


