# Generated by Django 4.2.2 on 2023-06-19 18:17

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pitch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.core.models.Pitch.upload_to_media_upload_path
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
