# Generated by Django 4.2.2 on 2023-06-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pitch_add_order_message_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='file_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
